name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java_version: [8, 11, 17]
        os: [windows-latest, macOS-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java_version }}
          distribution: 'zulu'

      - name: Make Maven Wrapper executable
        if: contains(matrix.os, 'win') == false && hashFiles('mvnw') != ''
        run: chmod +x ./mvnw
        
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        if: hashFiles('pom.xml') != ''
        run: ./mvnw package --file pom.xml --batch-mode
        env:
          MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn  
